### ISSUE TITLE
Image location hardcoded to "British Museum"

### ISSUE THREAD

**Issue by fkraeutli** [researchspace/researchspace#122]
When viewing an image in the Mirador viewer, the image location defaults to "British Museum". Is it possible to make this value customisable? Or if not, at least make it blank? Otherwise it appears to the user that all images are associated with the British Museum.

https://github.com/researchspace/researchspace/blob/23e41ae0e20bc0c369649d643f358f7cfb7354c9/src/main/web/components/iiif/ImageRegionEditor.ts#L267

**Comment by aindlq** [comment]
should be fixed as part of https://github.com/researchspace/researchspace/pull/123 change. For now we just make it blank and then think how to fix it properly. 

fyi you, can add `use-details-sidebar='true'` to `rs-iiif-mirador` and when you click on "i" icon in the viewer, instead of default mirador sidebar it will trigger our default details sidebar with image IRI as a parameter - https://github.com/researchspace/researchspace/blob/master/src/main/web/components/iiif/mirador/Mirador.ts#L151 . See default sidebar template - https://github.com/researchspace/researchspace/blob/master/src/main/resources/org/researchspace/apps/default/data/templates/http%253A%252F%252Fwww.researchspace.org%252Fresource%252FDetailsSidebar.html

ex:
![image](https://user-images.githubusercontent.com/2255044/95786594-9364da80-0ce0-11eb-9cb3-b9ca3a2c06fb.png)


It is much nicer than miradors default one because you can template the way you want:
![image](https://user-images.githubusercontent.com/2255044/95786731-d45cef00-0ce0-11eb-9d5b-e0681ef70e85.png)

**Comment by fkraeutli** [comment]
Great thanks! Will give it a try

**Comment by fkraeutli** [comment]
`use-details-sidebar='true'` doesn't work for me. It disables the usual sidebar but doesn't show a different one. Also tried adding the template manually but no luck

**Comment by aindlq** [comment]
mirdarod just sends an event, assuming that something listens to it. Are you sure that your page with IIIF is using default DetailsSidebar template or are you using your own template? Something like:

```
<div class="page">
    [[#> rsp:ClipboardSidebar]]
    [[#> rsp:DetailsSidebar]]
     Your IIIF component is here
    [[/rsp:DetailsSidebar]]
    [[/rsp:ClipboardSidebar]]
  [[/if]]
</div>
```

**Comment by aindlq** [comment]
Here is where event is triggered https://github.com/researchspace/researchspace/blob/master/src/main/web/components/iiif/mirador/Mirador.ts#L151 

As you can see it `BuiltInEvents.ComponentTemplateUpdate` to `['details-view', 'open-details-sidebar']`. These components can be found in the DetailsSidebar template - https://github.com/researchspace/researchspace/blob/master/src/main/resources/org/researchspace/apps/default/data/templates/http%253A%252F%252Fwww.researchspace.org%252Fresource%252FDetailsSidebar.html

One more thing, one the way DetailsSidebar works. It just loads resource page with additional `details` query param set to true. See https://github.com/researchspace/researchspace/blob/master/src/main/resources/org/researchspace/apps/default/data/templates/http%253A%252F%252Fwww.researchspace.org%252Fresource%252FDetailsSidebar.html#L34 .

So if you have template page for you resource you can do something like:
```
[[#if (urlParam "details")]]
<div class="detail-sidebar-content">
  put here template that you want to be rendered in details sidebar for the resource
</div>
[[else]]
  normal template when resource is open
[[/if]]
```

**Comment by fkraeutli** [comment]
Yes I noticed it just loaded the default page in the details sidebar. Thanks for clarifying!
