### ISSUE TITLE
built-in wikidata text lookup (sail federation) broken

### ISSUE THREAD

**Issue by lklic** [researchspace/researchspace#169]
When trying to implement the built-in wikidata-text lookup (ephedra) service, the platform does not build because the test query does not pass. The test queries do not send the expected parameters:

```
      sp:subject :_uri ;
      sp:predicate <http://www.researchspace.org/ontology/hasWikidataSearchToken> ;
      sp:object :_token
```

We should create an exception to these tests to exclude all repositories that are queried through federation, since an external service may be down this would prevent the platform from booting.

**Comment by gspinaci** [comment]
The issue seems to be here: https://github.com/researchspace/researchspace/blob/60233ec3181ff76c7dabb7a03a4e06b592db2166/src/main/java/org/researchspace/sail/rest/wikidata/WikidataSailConnection.java#L54-L58

We should have these URIs dynamically injected through the configuration and not harcoded in the code.

In particular, the code here checks that the query contains the property "hasWikidataSearchToken" and throws an exception if it hasn't provided. The service configuration can have a different URI for the same property resulting in a SailException.

https://github.com/researchspace/researchspace/blob/60233ec3181ff76c7dabb7a03a4e06b592db2166/src/main/java/org/researchspace/sail/rest/wikidata/WikidataSailConnection.java#L68-L76
